### ISSUE TITLE
init_renv() installs recommended packages that are too new

### ISSUE THREAD

**Issue by krlmlr** [cynkra/cynkrathis#15]
Witnessed today when initializing a repository with our current recommended snapshot. Several "recommended" packages (KernSmooth, class, ...) were too new, we were unable to restore this project in another machine.

**Comment by pat-s** [comment]
I've tried this in multiple R versions on our RSP instance with {cynkrathis} v0.2.0 and could not reproduce this. Please re-open if it stil applies.
