### ISSUE TITLE
Deal with IDE requirements

### ISSUE THREAD

**Issue by krlmlr** [cynkra/cynkrathis#27]
See https://github.com/rstudio/rstudio/commit/9e1d4997464716d2330a6b5aa25e0849fba0afa2#commitcomment-57191311.

Should we offer an easy way to ignore + untrack these infrastructure packages that might not be available in a suitable version in the current snapshot?

**Comment by pat-s** [comment]
Done by adding an additional repo to the library path which contains the minimum versions of the required packages.
