### ISSUE TITLE
Projects page is 404

### ISSUE THREAD

**Issue by IndrajeetPatil** [cynkra/cynkrathis#46]
Not sure if this is by design, but this is what I see on [this](https://www.cynkra.com/projects.html) page.

<img width="1321" alt="Screenshot 2022-10-17 at 15 59 33" src="https://user-images.githubusercontent.com/11330453/196197047-6742ae24-5f16-4eeb-8a5b-7f33c298f460.png">

**Comment by krlmlr** [comment]
Where is it linked from?

**Comment by pat-s** [comment]
Solved by using the new pkgdown theme.
