### ISSUE TITLE
Synchronize R versions with rocker

### ISSUE THREAD

**Issue by krlmlr** [cynkra/cynkrathis#52]
See `r-ver_x.y.z.Dockerfile` in https://github.com/rocker-org/rocker-versioned2/tree/master/dockerfiles .

This will make it a tad easier for us to switch between stacks. No urgency.

**Comment by pat-s** [comment]
For which purpose exactly? Being in control of the PM snapshots per R version ourselves is a feature - and I would not want to depend on rocker for this.

Also not sure if known but our own config for this lives in https://gitea.cynkra.com/docker/config/src/branch/main/r-versions and does not use {cynkrathis}.

**Comment by krlmlr** [comment]
Good idea. Thanks for the pointer.
