### ISSUE TITLE
Semantics of init_renv(local_packages = )

### ISSUE THREAD

**Issue by krlmlr** [cynkra/cynkrathis#6]
Should `local_packages` be a named vector instead? This would allow merging with `exclude_local` too.

**Comment by pat-s** [comment]
I was not convinced anymore by `local_packages()` - this got too complicated and fancy.

I think taking care of this by providing a minicran like repo for local packages is unavoidable in the long run anyways and we should not workaround a potential lack of such with too much effort.
`exclude` helps as a temporary workaround for initial scaffolding.
